### ISSUE TITLE
[EPIC] Search UX Improvements

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#281]
Description: 
A refactor of the user interface used to search and display metadata records to update underlying software dependencies and incorporate the latest version of GeoView to display geospatial data. 

Deliverables: 

- [ ] Work with Content Team to unify the GEO.ca theme with search application (app.geo.ca) for improved user experience
- [ ] Enhance the metadata details page for users of app.geo.ca based on WCAG accessibility standards
- [ ] Deployment of OGC API – Records on GEO.ca via pygeoapi as a standard for catalog interoperability. Coordinate release with Content Team
- [x] General improvements to the speed of the website, speed of returning metadata records, enabling caching on APIs where possible
- [x] Creation of UI elements on app.geo.ca to support data filtering (i.e., by ‘date’, ‘popularity’, ‘relevance’, etc.)
