### ISSUE TITLE
[EPIC] Infrastructure Renewal 

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#284]
Description: 
Renewal of various CCMEO APIs and infrastructure updates and upgrades, such as, the geolocator API, ISO Registry, Red Hat Enterprise Linux upgrades and others ad-hoc corporate requests

Deliverables: 
- [x] Geolocator API 
- [x] ISO Registry migration from GeoGratis to GEO.ca
- [x] RHEL 7 migration for the GeoNetwork catalog
- [x] RHEL 7 migration and upgrade of the Redmine issue tracker
