### ISSUE TITLE
[EPIC] Harvesting of Spatio-Temporal Asset Catalogs (STAC)

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#286]
Description:
Harvesting the NRCan CCMEO Data Cube and the Earth Observation Data Management System (EODMS) catalogs using the STAC standard and providing the user interface for users to search. 

Deliverables: 
- [x] Harvest the CCMEO Datacube
- [ ] Harvest the Earth Observation Data Management System (EODMS) 
- [ ] UI for users to perform a spatial and/or temporal search
- [ ] UI to view STAC records
- [ ] View EO thumbnails on app.geo.ca
