### ISSUE TITLE
[EPIC] Implementation of changes to UI/UX/Accessibility

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#377]
- [x] Develop a detailed plan for creating an integrated experience across Geo.ca 
- [x] Review with team
- [x] High Fidelity Wireframe / Clickable prototype 
- [x] Internal review and adjustments based on feedback 
- [x] User testing with High Fidelity prototype 
- [x] Analyzing test results and make changes as needed 
- [x] Create final user interface design 
- [x] Review & approvals 
- [x] Create final high fidelity clickable prototype 
- [x] Implementation based on mockups 
- [x] Verification and launch
